# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170607_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.Store'),
        ),
    ]
